CREATE TABLE T_USUARIOS (
    ID_USUARIO INTEGER PRIMARY KEY NOT NULL,
    NOME VARCHAR2(100) NOT NULL,
    CEP VARCHAR2(10) NOT NULL,
    EMAIL VARCHAR2(255) UNIQUE NOT NULL,
    SENHA VARCHAR2(100) NOT NULL,
    ROLE VARCHAR2(50) DEFAULT 'USER'
);


CREATE TABLE T_DRONES (
    ID_DRONE INTEGER PRIMARY KEY NOT NULL,
    MODELO VARCHAR2(150) NOT NULL,
    STATUS VARCHAR2(150) CHECK (STATUS IN ('ativo', 'inativo', 'manutenção')),
    DATA_AQUISICAO DATE
);


CREATE TABLE T_SOLICITACOES (
    ID_SOLICITACAO INTEGER PRIMARY KEY NOT NULL,
    DESCRICAO VARCHAR2(250) NOT NULL,
    DATA_SOLICITACAO DATE DEFAULT SYSDATE,
    STATUS VARCHAR2(150) CHECK (STATUS IN ('pendente', 'em andamento', 'concluída')),
    ID_DENUNCIANTE INTEGER,
    FOREIGN KEY (ID_DENUNCIANTE) REFERENCES T_USUARIOS(ID_USUARIO)
);

CREATE TABLE T_AREA_MAPEADA (
    ID_AREA INTEGER PRIMARY KEY NOT NULL,
    NOME_AREA VARCHAR(250) NOT NULL,
    LATITUDE DECIMAL(9,6) NOT NULL,
    LONGITUDE DECIMAL(9,6) NOT NULL,
    ID_DRONE INT NOT NULL,
    ID_COLETA INT NOT NULL,
    FOREIGN KEY (ID_DRONE) REFERENCES T_DRONES(ID_DRONE)
    FOREIGN KEY (ID_COLETA) REFERENCES T_COLETAS(ID_COLETA)
);


CREATE TABLE T_RESIDUOS (
    ID_RESIDUO INTEGER PRIMARY KEY NOT NULL,
    TIPO_RESIDUO VARCHAR(150) NOT NULL,
    DESCRICAO VARCHAR(150) NOT NULL,
    ID_AREA_MAPEADA INT NOT NULL,
    FOREIGN KEY (ID_AREA_MAPEADA) REFERENCES T_AREA_MAPEADA(ID_AREA)
);

CREATE TABLE T_COLETAS (
    ID_COLETA INTEGER PRIMARY KEY NOT NULL,
    DATA_COLETA DATE NOT NULL,
    QUANTIDADE_RESIDUO DECIMAL(10,2)
);

--
--CREATE TABLE T_AREA_SOLICITACAO (
--    ID_SOLICITACAO INT,
--    ID_AREA INT,
--    PRIMARY KEY (id_solicitacao, id_area),
--    FOREIGN KEY (id_solicitacao) REFERENCES solicitacao(id_solicitacao),
--    FOREIGN KEY (id_area) REFERENCES area_mapeada(id_area)
--);



