CREATE SEQUENCE SEQ_ID
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

CREATE TABLE T_USUARIOS (
    ID_USUARIO INTEGER DEFAULT SEQ_USUARIOS.NEXTVAL NOT NULL,
    NOME VARCHAR2(100) NOT NULL,
    CEP VARCHAR(10) NOT NULL,
    EMAIL VARCHAR2(100) UNIQUE NOT NULL,
    SENHA VARCHAR2(100) NOT NULL,
    ROLE VARCHAR2(50) DEFAULT 'USER'
);

CREATE TABLE T_DRONES (
    ID_DRONE INT PRIMARY KEY,
    MODELO VARCHAR(150) NOT NULL,
    STATUS VARCHAR(150) CHECK (status IN ('ativo', 'inativo', 'manutenção')),
    data_aquisicao DATE
);

CREATE TABLE T_RESIDUOS (
    ID_RESIDUO INT PRIMARY KEY,
    TIPO_RESIDUO VARCHAR(150) NOT NULL,
    DESCRICAO VARCHAR(150) NOT NULL
);

CREATE TABLE T_SOLICITACOES (
    ID_SOLICITACAO INT PRIMARY KEY,
    DESCRICAO VARCHAR(250) NOT NULL,
    DATA_SOLICITACAO DATE DEFAULT SYSDATE,
    STATUS VARCHAR(150) CHECK (status IN ('pendente', 'em andamento', 'concluída'))
);



CREATE TABLE T_COLETAS (
    ID_COLETA INT PRIMARY KEY,
    ID_AREA INT NOT NULL,
    ID_RESIDUO INT NOT NULL,
    DATA_COLETA DATE NOT NULL,
    QUANTIDADE_RESIDUO DECIMAL(10,2), -- quantidade em kg
    FOREIGN KEY (id_area) REFERENCES area_mapeada(id_area),
    FOREIGN KEY (id_residuo) REFERENCES residuos(id_residuo)
);

CREATE TABLE T_AREA_MAPEADA (
    ID_AREA INT PRIMARY KEY,
    NOME_AREA VARCHAR(250) NOT NULL,
    LATITUDE DECIMAL(9,6) NOT NULL,
    LONGITUDE DECIMAL(9,6) NOT NULL,
    ID_DRONE INT NOT NULL,
    FOREIGN KEY (id_drone) REFERENCES drones(id_drone)
);


CREATE TABLE T_AREA_SOLICITACAO (
    id_solicitacao INT,
    id_area INT,
    PRIMARY KEY (id_solicitacao, id_area),
    FOREIGN KEY (id_solicitacao) REFERENCES solicitacao(id_solicitacao),
    FOREIGN KEY (id_area) REFERENCES area_mapeada(id_area)
);



